package io.github.arkosammy12.cli;

import io.github.arkosammy12.core.assembler.OctoAssembler;
import io.github.arkosammy12.core.assembler.OctoAssemblyStage;
import io.github.arkosammy12.core.result.OctoAssemblerResult;
import io.github.arkosammy12.core.result.OctoCodegenResult;
import io.github.arkosammy12.core.elements.CodeElement;
import io.github.arkosammy12.core.lexer.*;
import io.github.arkosammy12.core.result.OctoParserResult;

import java.util.Collection;
import java.util.List;

import static io.github.arkosammy12.core.assembler.OctoAssembler.byteArrayToString;

public class Main {

    static void main(String[] args) {
        String test = """
                # 1dcell disassembler output generated by the
                # Cadmium decompiler 
                
                : main
                        jump label_2
                
                
                : sprite_0
                        0b10000000
                
                : sub_0
                        vc += 0x01
                        vd := 0x00
                
                : label_0
                        sub_1
                        v8 := 0x01
                        if v9 != 0x00 then
                            sub_2
                        v8 &= va
                        if v8 != 0x00 then
                            sprite vd vc 0x1
                        vd += 0x01
                        if vd != 0x40 then
                            jump label_0
                        vb += 0x01
                        vd := 0x00
                        return
                
                : sub_1
                        v9 := 0x00
                        v0 := vd
                        sprite v0 vb 0x1
                        if vf == 0x01 then
                            v9 += 0x02
                        sprite v0 vb 0x1
                        v0 += 0xff
                        sprite v0 vb 0x1
                        if vf == 0x01 then
                            v9 += 0x04
                        sprite v0 vb 0x1
                        v0 += 0x02
                        sprite v0 vb 0x1
                        if vf == 0x01 then
                            v9 += 0x01
                        sprite v0 vb 0x1
                        return
                
                : sub_2
                        v2 := 0x00
                
                : label_1
                        v8 <<= v8
                        v2 += 0x01
                        vf := v9
                        vf =- v2
                        if vf == 0x00 then
                            jump label_1
                        return
                
                : sub_3
                        clear
                        vd := 0x00
                        vc := 0x05
                        vb := vc
                        va += 0x01
                        sub_4
                        v0 := 0x1f
                        v1 := vc
                        i := sprite_0
                        sprite v0 v1 0x1
                        return
                
                : sub_4
                        v0 := va
                        i := data_0
                        bcd v0
                        load v2
                        v4 := 0x00
                        i := hex v0
                        v3 := 0x00
                        sprite v3 v4 0x5
                        i := hex v1
                        v3 += 0x05
                        sprite v3 v4 0x5
                        i := hex v2
                        v3 += 0x05
                        sprite v3 v4 0x5
                        return
                
                
                : data_0
                        0x00 0x00 0x00
                : label_2
                        va := 0x14
                        sub_3
                
                : label_3
                        sub_0
                        if vc == 0x1f then
                            sub_3
                        jump label_3
                """;

        SourceFile sourceFile = new SourceFile(List.of(test.split("\n")));
        OctoAssembler assembler = new OctoAssembler(0x200, OctoAssemblyStage.CODEGEN);
        switch (assembler.assemble(sourceFile)) {
            case OctoParserResult.Ok(Collection<CodeElement> codeElements, _, _) -> codeElements.forEach(IO::println);
            case OctoCodegenResult.Ok(byte[] rom) -> IO.println(byteArrayToString(rom));
            case OctoAssemblerResult.Error error -> IO.println("""
                Assembly error!
                %s %s
                """.formatted(error.getSourcePosition().map(position -> "(%d:%d)".formatted(position.row() + 1, position.column() + 1)).orElse(""), error.getError()));
            default -> {}
        }
    }

}
